# -*- coding: utf-8 -*-
"""Prompt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h3lhwxcy4GdKNCtNMqz4tQ_S5lgYbSXD
"""



!pip install openai

!pip install gradio

import openai
import gradio

# Additional API Key
# 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

openai.api_key = "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"

messages = [{"role": "system", "content": "You food is my food"}]

def CustomChatGPT(user_input):
    messages.append({"role": "user", "content": user_input})
    response = openai.ChatCompletion.create(
        model = "gpt-3.5-turbo",
        messages = messages
    )
    ChatGPT_reply = response["choices"][0]["message"]["content"]
    messages.append({"role": "assistant", "content": ChatGPT_reply})
    return ChatGPT_reply

demo = gradio.Interface(fn=CustomChatGPT, inputs = "text", outputs = "text", title = "Recipie Pirio")

demo.launch(share=True)

text = input()
completion = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages=[{"role": "user", "content": f"Give me the recipie of {text} in india"}])
print(completion.choices[0].message.content)

